name: Create and Auto merge PR
on:
  push:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  create_auto_merge_pr:
    name: create-auto-merge-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create-change
        run: |
          echo $(date) >> date
          echo ${{ secrets.SECRET_CODE }} >> secret

      - name: create-pr
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          # delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # branch-suffix: short-commit-hash
          # title: "Create random PR"
          # body: |
          #   ## What is it?

          #   Just Kavi is playing with Github Action and Automerge features

          # labels: github-action, automatic
          # branch: automerge-play
      - name: enable auto merge
        # Doesn't merge, but only enable "auto-merge"
        run: gh pr merge --auto --merge "${{ steps.create_pr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: access secret code
        run: echo printing very secret code ${{ secrets.SECRET_CODE }}
      # - name: approve pr
      #   run: gh pr review "${PULL_REQUEST_NUMBER}" --approve -b "**Approving** vendoring Loki"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
